/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ptithcm.qlshopapp.App.BackFrame.QuanLy;

import com.ptithcm.qlshopapp.DAO.Dao_SanPham;
import com.ptithcm.qlshopapp.Model.SanPham;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class GDDanhSachSP extends javax.swing.JFrame {

    /**
     * Creates new form GDDanhSachSP
     */
    private List<SanPham> lsp ;
    DefaultTableModel model  ;
    public GDDanhSachSP() {
        initComponents();
        btnXoaSP.setEnabled(false);
        this.setLocation(700, 100);
        initTable() ;
        fillTable() ;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDSSP = new javax.swing.JTable();
        btnXoaSP = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        cbSapxepSP = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Danh Sách Sản Phẩm");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setText("Tìm kiếm:");

        tblDSSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tblDSSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSSPMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDSSP);

        btnXoaSP.setText("Xóa sản phẩm");
        btnXoaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaSPActionPerformed(evt);
            }
        });

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        cbSapxepSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mặc định", "Theo Tên", "Theo Kích Thước", "Theo Số Lượng", "Theo Giá" }));
        cbSapxepSP.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbSapxepSPItemStateChanged(evt);
            }
        });

        jLabel3.setText("Sắp xếp:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbSapxepSP, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(btnXoaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSapxepSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        this.setVisible(false);
        GDQuanLy obj = new GDQuanLy() ;
        obj.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnXoaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaSPActionPerformed
        int dig = JOptionPane.showConfirmDialog(this, "Xác nhận xóa sản phẩm","Xóa sản phẩm",JOptionPane.YES_NO_OPTION);
        if (dig == JOptionPane.YES_OPTION) {
            String maSP = model.getValueAt(tblDSSP.getSelectedRow(), 0).toString() ;
            Dao_SanPham dao = new Dao_SanPham() ;
            try {
                dao.XoaSanPham(maSP) ;
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Lỗi SQL DAO_SANPHAM", "SQL ERROR", JOptionPane.ERROR_MESSAGE);
            }
            fillTable();
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnXoaSPActionPerformed

    private void cbSapxepSPItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbSapxepSPItemStateChanged
        if(cbSapxepSP.getSelectedItem().toString().compareTo("Mặc định")==0){
            fillSeclectionTable(lsp);
        } else if(cbSapxepSP.getSelectedItem().toString().compareTo("Theo Tên") == 0) {
            Dao_SanPham dao = new Dao_SanPham() ;
            List<SanPham> tenlsp = new ArrayList<>() ;
            try {
                tenlsp = dao.SapXepSP(1) ;
            } catch (Exception ex) {
                Logger.getLogger(GDDanhSachSP.class.getName()).log(Level.SEVERE, null, ex);
            }
            fillSeclectionTable(tenlsp);
        } else if (cbSapxepSP.getSelectedItem().toString().compareTo("Theo Kích Thước") == 0) {
            Dao_SanPham dao = new Dao_SanPham() ;
            List<SanPham> kichthuoclsp = new ArrayList<>() ;
            try {
                kichthuoclsp = dao.SapXepSP(2) ;
            } catch (Exception ex) {
                Logger.getLogger(GDDanhSachSP.class.getName()).log(Level.SEVERE, null, ex);
            }
            fillSeclectionTable(kichthuoclsp);
        } else if (cbSapxepSP.getSelectedItem().toString().compareTo("Theo Số Lượng") == 0) {
            Dao_SanPham dao = new Dao_SanPham() ;
            List<SanPham> sluonglsp = new ArrayList<>() ;
            try {
                sluonglsp = dao.SapXepSP(3) ;
            } catch (Exception ex) {
                Logger.getLogger(GDDanhSachSP.class.getName()).log(Level.SEVERE, null, ex);
            }
            fillSeclectionTable(sluonglsp);
        } else {
            Dao_SanPham dao = new Dao_SanPham() ;
            List<SanPham> gialsp = new ArrayList<>() ;
            try {
                gialsp = dao.SapXepSP(4) ;
            } catch (Exception ex) {
                Logger.getLogger(GDDanhSachSP.class.getName()).log(Level.SEVERE, null, ex);
            }
            fillSeclectionTable(gialsp);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSapxepSPItemStateChanged

    private void tblDSSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSSPMouseClicked
        btnXoaSP.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_tblDSSPMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GDDanhSachSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GDDanhSachSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GDDanhSachSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GDDanhSachSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GDDanhSachSP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoaSP;
    private javax.swing.JComboBox<String> cbSapxepSP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDSSP;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables

    private void initTable() {
        model = (DefaultTableModel) tblDSSP.getModel() ;
        model.setColumnIdentifiers(new Object[] {
            "MÃ","TÊN SẢN PHẨM","SỐ LƯỢNG","GIÁ","KÍCH THƯỚC"
        });
        model.setRowCount(0);
        tblDSSP.getColumnModel().getColumn(0).setPreferredWidth(50);
        tblDSSP.getColumnModel().getColumn(1).setPreferredWidth(200);
        tblDSSP.getColumnModel().getColumn(2).setPreferredWidth(100);
        tblDSSP.getColumnModel().getColumn(3).setPreferredWidth(100);
        tblDSSP.getColumnModel().getColumn(4).setPreferredWidth(80);
    }

    private void fillTable() {
        Dao_SanPham dao = new Dao_SanPham() ;
        try {
            lsp = dao.getListSP() ;
        } catch (Exception ex) {
            Logger.getLogger(GDDanhSachSP.class.getName()).log(Level.SEVERE, null, ex);
        }
        model.setRowCount(0);
        for(SanPham sp : lsp) {
            Object[] row = new Object[] {
                sp.getMasp() , sp.getTensp() , sp.getSlTon(), sp.getGia() , sp.getKichThuoc()
            } ;
            model.addRow(row);
        }
    }
    private  void fillSeclectionTable(List<SanPham> lsp) {
        model.setRowCount(0);
        for(SanPham sp: lsp) {
            Object[] row = new Object[]{
              sp.getMasp() , sp.getTensp() , sp.getSlTon() , sp.getGia() , sp.getKichThuoc()
            };
            model.addRow(row);
        }
    }
}
