/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ptithcm.qlshopapp.App.BackFrame.QuanLy;

import com.ptithcm.qlshopapp.DAO.Dao_HoaDon;
import com.ptithcm.qlshopapp.Model.HoaDon;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class GDXemHoaDon extends javax.swing.JFrame {

    /**
     * Creates new form GDXemHoaDon
     */
    private List<HoaDon> lhd ;
    DefaultTableModel model;
    public GDXemHoaDon() {
        initComponents();
        this.setLocation(700, 100);
        initTable() ;
        lhd = new ArrayList<>() ;
        
        fillTable() ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHD = new javax.swing.JTable();
        btnSXDoanhThu = new javax.swing.JButton();
        btnSXTheoNgay = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        btndsMĐ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setForeground(new java.awt.Color(255, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Danh Sách Hóa Đơn");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        tblHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tblHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHDMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHD);

        btnSXDoanhThu.setText("Sắp xêp theo doanh số");
        btnSXDoanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSXDoanhThuActionPerformed(evt);
            }
        });

        btnSXTheoNgay.setText("Sắp xếp theo ngày");
        btnSXTheoNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSXTheoNgayActionPerformed(evt);
            }
        });

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btndsMĐ.setText("Mặc định");
        btndsMĐ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndsMĐActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(btnSXDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(btndsMĐ, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSXTheoNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSXDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSXTheoNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndsMĐ, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHDMouseClicked

        String id =  model.getValueAt(tblHD.getSelectedRow(), 0).toString() ;
        HoaDon sHD = new HoaDon() ;
        for(HoaDon thd : lhd) {
            if (thd.getMahd().compareTo(id) == 0) {
                sHD = thd ;
            }
        }
        GDChiTietHoaDon obj = new GDChiTietHoaDon(sHD );
        obj.setVisible(true);
        

        // TODO add your handling code here:
    }//GEN-LAST:event_tblHDMouseClicked

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        this.setVisible(false);
        GDQuanLy obj = new GDQuanLy() ;
        obj.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnSXDoanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSXDoanhThuActionPerformed
        List<HoaDon> sLHD = new ArrayList<>() ;
        Dao_HoaDon dao = new Dao_HoaDon() ;
        try {
            sLHD = dao.getListHDDoanhTHu() ;
        } catch (Exception ex) {
            Logger.getLogger(GDXemHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }
        fillButton(sLHD);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSXDoanhThuActionPerformed

    private void btndsMĐActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndsMĐActionPerformed
        fillButton(lhd);
        // TODO add your handling code here:
    }//GEN-LAST:event_btndsMĐActionPerformed

    private void btnSXTheoNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSXTheoNgayActionPerformed
        List<HoaDon> sLHD = new ArrayList<>() ;
        Dao_HoaDon dao = new Dao_HoaDon() ;
        try {
            sLHD = dao.getListHDDate() ;
        } catch (Exception ex) {
            Logger.getLogger(GDXemHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }
        fillButton(sLHD);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSXTheoNgayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GDXemHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GDXemHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GDXemHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GDXemHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GDXemHoaDon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSXDoanhThu;
    private javax.swing.JButton btnSXTheoNgay;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btndsMĐ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHD;
    // End of variables declaration//GEN-END:variables

    private void initTable() {
       model = (DefaultTableModel) tblHD.getModel() ;
       model.setColumnIdentifiers(new Object[] {
           "MAHD","NGAY","TONGTIEN","TENKHACHHANG","SĐT"
       });
       model.setRowCount(0);
       tblHD.getColumnModel().getColumn(0).setPreferredWidth(50);
       tblHD.getColumnModel().getColumn(1).setPreferredWidth(70);
       tblHD.getColumnModel().getColumn(2).setPreferredWidth(150);
       tblHD.getColumnModel().getColumn(3).setPreferredWidth(140);
       tblHD.getColumnModel().getColumn(4).setPreferredWidth(100);
    }

    private void fillTable() {
        Dao_HoaDon dao = new Dao_HoaDon() ;
        try {
            lhd = dao.getAllHoaDons() ;
        } catch (Exception ex) {
            Logger.getLogger(GDXemHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }
        model.setRowCount(0);
        for(HoaDon hd : lhd) {
            Object[] row = new Object[] {
                hd.getMahd(), hd.getNgay(), hd.getTongtien(), hd.getTenkhachhang(), hd.getSdtkh() 
            };
            model.addRow(row);
        }
    }
    private void fillButton (List<HoaDon> slhd) {
        model.setRowCount(0);
        for(HoaDon hd : slhd) {
            Object[] row = new Object[] {
                hd.getMahd(), hd.getNgay(), hd.getTongtien(), hd.getTenkhachhang(), hd.getSdtkh() 
            };
            model.addRow(row);
        }
    }
}
